### ISSUE TITLE
各种报错，运行不了啊

### ISSUE THREAD

**Issue by xxxxxx-oss** [M-Kings/BypassAv-web#2]
![image](https://user-images.githubusercontent.com/62422553/109411941-41e39080-79e0-11eb-87b8-0129754947df.png)
然后创建了files文件夹后
![image](https://user-images.githubusercontent.com/62422553/109411980-722b2f00-79e0-11eb-8a9d-79f1a1ef3fa7.png)

**Comment by NickYan7** [comment]
先在 .\ 新建一个 `files` 目录，然后修改 .\nim\views.py 第 7 行为相对路径即可。

![Capture20210301103903](https://user-images.githubusercontent.com/27906343/109445484-a6ebc480-7a7a-11eb-9b49-67abbc5263a7.png)

**Comment by xxxxxx-oss** [comment]
> 0.\已恢复的。\视图.py 7个位置`files`
> 
> ![Capture20210301103903](https://user-images.githubusercontent.com/27906343/109445484-a6ebc480-7a7a-11eb-9b49-67abbc5263a7.png)

还是不行呢，改完之后：
生成文件时windows下的报错
![image](https://user-images.githubusercontent.com/62422553/109448163-452e5900-7a80-11eb-806d-9919ab8b12f0.png)
 linux下的报错
![image](https://user-images.githubusercontent.com/62422553/109448352-b3731b80-7a80-11eb-80ae-799376ea1f07.png)

**Comment by ck00004** [comment]
不支持windows下部署  linux下的错误你可以换一下版本 我用的是python3.5.2
