### ISSUE TITLE
看下这个报错？

### ISSUE THREAD

**Issue by NickYan7** [M-Kings/BypassAv-web#3]
nim 和 winim 均已安装，gcc/g++ 正常，这个报错看起来好像是 nim 的问题？

![error](https://user-images.githubusercontent.com/27906343/109448076-1fa14f80-7a80-11eb-9e1e-2f8b18a05084.png)
![error2](https://user-images.githubusercontent.com/27906343/109448081-20d27c80-7a80-11eb-8a26-60ed12d8a90e.png)

**Comment by ck00004** [comment]
服务端不支持 windows安装 看报错应该是 winim的问题 这个报错不全 截nim编译部分的报错
