### ISSUE TITLE
[WinError 3] 系统找不到指定的路径。: 'files/'

### ISSUE THREAD

**Issue by TryA9ain** [M-Kings/BypassAv-web#4]
python 3.8.5 运行报错
![image](https://user-images.githubusercontent.com/51145610/110203747-cd5e9500-7eaa-11eb-8a43-30f428c9b0ee.png)
![image](https://user-images.githubusercontent.com/51145610/110203752-d485a300-7eaa-11eb-97ba-95da614b9553.png)

**Comment by ck00004** [comment]
``.\``目录下创建 files文件 不支持windows mac下部署 服务器端
